site_name: Eksploracja i przetwarzanie dużych zbiorów danych
site_url: https://example.com
theme:
  name: material
  palette:

    - scheme: slate
      primary: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

    - scheme: default
      primary: light blue
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
